# Generated by Django 5.2.17 on 2026-09-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetsegment',
            name='has_cctv',
            field=models.BooleanField(default=False, help_text='Street is covered by public CCTV cameras (drives the CCTV-priority preference).'),
        ),
    ]
